apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oa07m238f-java-quarkus
  janus-idp.io/tekton: oa07m238f-java-quarkus
  backstage.io/kubernetes-id: oa07m238f-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oa07m238f-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
